default: &default
  adapter: postgresql
  # puma默认线程是16 连接数应与线程数对应
  pool: 16
  encoding: unicode
  timeout: 5000
  username: <%= ENV['DB_USER'] || 'fugeng' %>
  password: <%= ENV['DB_PASS']%>

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
