default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000
  username: <%= ENV['DB_USER'] || 'fugeng' %>
  password: <%= ENV['DB_PASS']%>

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
